all:

	gcc guess_number_server.c -o guess_number_server
	gcc guess_number_client.c -o guess_number_client
	gcc -pthread -o blackjack_server blackjack_server.c
	gcc blackjack_client.c -o blackjack_client
	gcc -pthread -o game_system_server game_system_server.c
	gcc game_system_client.c -o game_system_client

